project:
  type: website
  output-dir: docs

website:
  title: "Ericka F. Salas-Garcia"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - about.qmd

format:
  html:
    theme: minty
    css: styles.css

editor: visual